<a href="https://colab.research.google.com/github/RCDayrit/LinearAlgebra2021/blob/main/assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ECE

##Laboratory 6

### Objectives

At the end of this activity you will be able to:

    1. Be familiar with the fundamental matrix operations.
    2. Apply the operations to solve intermediate equations.
    3. Apply matrix algebra in engineering solutions.

In [6]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition

In [10]:
$$ A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

SyntaxError: ignored

In [9]:
A = np.array([
      [1,2,5],
      [2,-1,0],
      [0,-3,3]        
])

In [13]:
AT1 = np.transpose(A)
AT1

array([[ 1,  2,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [14]:
AT2 = A.T
AT2

array([[ 1,  2,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [15]:
np.array_equiv(AT1, AT2)

True

In [17]:
B = np.array ([
     [1,2,3,4],
     [1,0,2,1],    
])

B.shape

(2, 4)

In [18]:
np.transpose(B).shape

(4, 2)

In [19]:
B.T.shape

(4, 2)

In [39]:
C = np.array ([
     [1,2,3],
     [1,0,2],
     [3,2,1],
     [9,3,2]    
])

C.shape

(4, 3)

In [21]:
AT3 = np.transpose(C)
AT3

array([[1, 1, 3, 9],
       [2, 0, 2, 3],
       [3, 2, 1, 2]])

In [22]:
AT4 = A.T
AT4

array([[ 1,  2,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [23]:
np.array_equiv(AT3, AT4)

False

In [24]:
np.transpose(C).shape

(3, 4)

In [26]:
C.T.shape

(3, 4)

# Dot Product

In [27]:
X = np.array([
    [1,2],
    [0,1]
])
Y = np.array([
    [-1,0],
    [2,2]
])

In [28]:
np.dot(X,Y)

array([[3, 4],
       [2, 2]])

In [29]:
X.dot(Y)

array([[3, 4],
       [2, 2]])

In [30]:
 X @ Y

array([[3, 4],
       [2, 2]])

In [31]:
np.matmul(X,Y)

array([[3, 4],
       [2, 2]])

In [38]:
D = np.array([
    [3,2,2],
    [3,1,3],
    [5,3,2]
])
E = np.array([
    [-2,0,5],
    [2,4,6],
    [7,4,3]
])

In [35]:
np.dot(D,E)

array([[12, 16, 33],
       [17, 16, 30],
       [10, 20, 49]])

In [36]:
D.dot(E)

array([[12, 16, 33],
       [17, 16, 30],
       [10, 20, 49]])

In [37]:
D @ E

array([[12, 16, 33],
       [17, 16, 30],
       [10, 20, 49]])

In [33]:
np.matmul(D,E)

array([[12, 16, 33],
       [17, 16, 30],
       [10, 20, 49]])

# Rule 1

In [40]:
A = np.array([
    [2,4],
    [5,-2],
    [0,1]          

])
B = np.array([
    [1,1],
    [3,3],
    [-1,-2]          

])
C = np.array([
    [0,1,1],
    [1,1,2]         

])
print(A.shape)
print(B.shape)
print(C.shape)

(3, 2)
(3, 2)
(2, 3)


In [41]:
A @ C 

array([[ 4,  6, 10],
       [-2,  3,  1],
       [ 1,  1,  2]])

In [42]:
B @ C

array([[ 1,  2,  3],
       [ 3,  6,  9],
       [-2, -3, -5]])

In [44]:
X = np.array([
    [1,2,3,0]         

])
Y = np.array([
    [1,0,4,-1]         

])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [45]:
Y.T @ X

array([[ 1,  2,  3,  0],
       [ 0,  0,  0,  0],
       [ 4,  8, 12,  0],
       [-1, -2, -3,  0]])

In [46]:
X @ Y.T

array([[13]])

# Rule 2

In [50]:
A = np.array([
    [7,5,3],
    [9,1,2],
    [6,4,2]          

])

B = np.array([
    [2,9,6],
    [-2,5,6],
    [9,2,4]         

])
C = np.array([
    [6,7,9],
    [-5,6,8],
    [2,1,1]         

])
print(A.shape)
print(B.shape)
print(C.shape)

(3, 3)
(3, 3)
(3, 3)


In [53]:
np.array_equal(A@B, B@A)

False

In [55]:
E = A @ (B@C)
E

array([[-116,  865, 1115],
       [-110,  846, 1094],
       [-122,  690,  890]])

In [57]:
F = (A @ B) @C
F

array([[-116,  865, 1115],
       [-110,  846, 1094],
       [-122,  690,  890]])

In [ ]:
np.array_equi

In [59]:
np.array_equiv(E,F)

True

In [51]:
np.array_equal(a_dot_z,z_mat)

NameError: ignored

In [48]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[4.64303989e-310 2.29175545e-312 1.29441743e-312]
 [2.33419537e-312 9.76118064e-313 2.41907520e-312]
 [2.05833592e-312 7.85323066e+020 1.19629504e+180]]


NameError: ignored

In [60]:
A = np.array([
    [1,4],
    [0,3]
])
np.linalg.det(A)

3.0000000000000004

In [62]:
B = np.array([
    [1,5,2],
    [3,-1,-1],
    [0,-2,1]          

])
np.linalg.det(B)

-30.000000000000014